const ADD_VILLAIN = "ADD_VILLAIN"
const ARREST_VILLAIN = "ARREST_VILLAIN"
const ADD_MORIARTY_LOCATION = "ADD_MORIARTY_LOCATION"


export { 
    ADD_VILLAIN,
    ARREST_VILLAIN,
    ADD_MORIARTY_LOCATION

}